# Menggunakan image nginx untuk menyajikan file frontend statis
FROM nginx:alpine

# Salin file nginx.conf yang disesuaikan ke dalam container
COPY nginx/nginx.conf /etc/nginx/nginx.conf

# Salin seluruh folder frontend ke dalam folder nginx default
COPY frontend/ /usr/share/nginx/html/

# Menetapkan port untuk akses frontend
EXPOSE 80

# Nginx akan otomatis menjalankan server ketika container dimulai